"""Unit tests for scripts/merge_daily_brief_postprocess.py tail helpers."""

from __future__ import annotations

import importlib.util
from pathlib import Path

def _load_merge_module():
    root = Path(__file__).resolve().parent.parent
    path = root / "scripts" / "merge_daily_brief_postprocess.py"
    spec = importlib.util.spec_from_file_location("merge_daily_brief_postprocess", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

def test_sanitize_postprocess_tail_strips_duplicate_outline_before_section_8():
    mod = _load_merge_module()
    tail = (
        "## 2c. Narrative layer retrofit (Grok mirror with evidence contract)\n\n"
        "### Bottom line\n\nkeep me.\n\n"
        "## 3. Lead themes (auto-stub — replace after reading)\n\n"
        "### Work-politics\nstub\n\n"
        "## 7. Context efficiency (operator)\n\nbullets\n\n"
        "## 8. Quality rubric footer (optional)\n\n| x | y |\n"
    )
    out = mod._sanitize_postprocess_tail(tail)
    assert "## 3. Lead themes" not in out
    assert "## 7. Context efficiency" not in out
    assert "keep me." in out
    assert "## 8. Quality rubric footer" in out

def test_sanitize_postprocess_tail_noop_when_no_duplicate_stub():
    mod = _load_merge_module()
    tail = "## 2c. Narrative layer retrofit\n\n### x\n\n## 8. Quality rubric footer (optional)\n\n| a | b |\n"
    assert mod._sanitize_postprocess_tail(tail) == tail

def test_strip_trailing_generator_signature():
    mod = _load_merge_module()
    tail = (
        "## 2c. Narrative layer retrofit\n\nbody\n\n"
        "## 8. Quality rubric footer (optional)\n\n| T | 1 |\n\n"
        "---\n\n"
        "_Generated by `scripts/generate_work_politics_daily_brief.py` "
        "(legacy alias: `generate_wap_daily_brief.py`); "
        "config `docs/archive/skill-work-legacy/work-strategy/daily-brief-config.json`._\n"
    )
    out = mod._strip_trailing_generator_signature(tail)
    assert "_Generated by" not in out
    assert "## 8. Quality rubric footer" in out

def test_sanitize_postprocess_tail_noop_when_stub_present_but_no_section_8_after():
    """Duplicate ## 3 stub without a following ## 8: do not strip (ambiguous)."""
    mod = _load_merge_module()
    tail = (
        "## 2c. Narrative layer retrofit\n\n### x\n\n"
        "## 3. Lead themes (auto-stub — replace after reading)\n\n"
        "### Work-politics\nstub only\n"
    )
    assert mod._sanitize_postprocess_tail(tail) == tail

def test_sanitize_postprocess_tail_noop_when_section_8_before_stub():
    """## 8 appears before duplicate ## 3 (malformed): first ## 8 wins; no strip."""
    mod = _load_merge_module()
    tail = (
        "## 2c. Narrative layer retrofit\n\n"
        "## 8. Quality rubric footer (optional)\n\n| a | 1 |\n\n"
        "## 3. Lead themes (auto-stub — replace after reading)\n\noops\n"
    )
    assert mod._sanitize_postprocess_tail(tail) == tail

def test_strip_trailing_generator_signature_noop_when_signature_not_at_eof():
    """Footer line only matches at end of tail; mid-body copy is preserved."""
    mod = _load_merge_module()
    sig = (
        "\n\n---\n\n"
        "_Generated by `scripts/generate_work_politics_daily_brief.py` "
        "(legacy alias: `generate_wap_daily_brief.py`); "
        "config `docs/archive/skill-work-legacy/work-strategy/daily-brief-config.json`._\n"
    )
    tail = "## 2c.\n\nSee also:" + sig + "More prose after duplicate footer line.\n"
    assert mod._strip_trailing_generator_signature(tail) == tail
