"""Render CLAIMS-OVERVIEW.md from claims/registry/claims.jsonl."""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORK_DIR = ROOT / "codex" / "predictive-history"
CLAIMS = WORK_DIR / "claims" / "registry" / "claims.jsonl"
OUT = WORK_DIR / "CLAIMS-OVERVIEW.md"

def load_rows() -> list[dict]:
    rows = []
    if not CLAIMS.exists():
        return rows
    with CLAIMS.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows

def main() -> int:
    rows = load_rows()
    by_type = Counter(r.get("claim_type") for r in rows)
    by_status = Counter(r.get("status") for r in rows)
    predictive = [r for r in rows if r.get("claim_type") == "predictive"]
    non_pred = [r for r in rows if r.get("claim_type") != "predictive"]
    missing_chapter = [r for r in rows if not r.get("chapter_candidates")]
    no_source = [r for r in rows if not r.get("source_id")]

    lines = [
        "# Claims overview",
        "",
        f"**Total claims:** {len(rows)}",
        "",
        "## By claim_type",
        "",
    ]
    for k, v in sorted(by_type.items(), key=lambda x: (-x[1], x[0] or "")):
        lines.append(f"- **{k}:** {v}")
    lines += ["", "## By status", ""]
    for k, v in sorted(by_status.items(), key=lambda x: (-x[1], x[0] or "")):
        lines.append(f"- **{k}:** {v}")
    lines += [
        "",
        "## Predictive vs non-predictive",
        "",
        f"- **Predictive:** {len(predictive)}",
        f"- **Non-predictive:** {len(non_pred)}",
        "",
        "## Gaps",
        "",
    ]
    if missing_chapter:
        lines.append("### Missing chapter_candidates")
        for r in missing_chapter:
            lines.append(f"- `{r.get('claim_id')}` — {r.get('claim', '')[:80]}…")
        lines.append("")
    else:
        lines.append("- No rows missing `chapter_candidates`.")
        lines.append("")
    if no_source:
        lines.append("### Missing source_id")
        for r in no_source:
            lines.append(f"- `{r.get('claim_id')}`")
        lines.append("")
    lines.append(
        "*Generated by `scripts/work_jiang/render_claims_overview.py` — run after editing `claims/registry/claims.jsonl`.*"
    )
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
