#!/usr/bin/env python3
"""Compress a SYSTEM_PROMPT for small-context local models.

Reads the full SYSTEM_PROMPT from archive/grace-mar-instance/bot/prompt.py and produces a compressed
variant that fits within a configurable token budget. Strategy:

  1. Keep identity core (WHO YOU ARE, HOW YOU TALK, VALUES)
  2. Keep knowledge boundary and constraints (critical for governance)
  3. Summarize IX-A/B/C entries to top-N by section size
  4. Drop lookup/rephrase scaffolding (not needed without cloud search)
  5. Drop analyst prompt (governance runs separately or not at all on local)

The output is a Python file with SYSTEM_PROMPT_COMPRESSED that can be
imported by local-mode bots.

Usage:
    python scripts/compress_system_prompt.py
    python scripts/compress_system_prompt.py --budget 4000
    python scripts/compress_system_prompt.py --output archive/grace-mar-instance/bot/prompt_compressed.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

def _estimate_tokens(text: str) -> int:
    """Rough token estimate: ~4 chars per token for English."""
    return len(text) // 4

def _extract_sections(prompt: str) -> dict[str, str]:
    """Split the system prompt into named sections by ## headers."""
    sections: dict[str, str] = {}
    current_name = "_preamble"
    current_lines: list[str] = []

    for line in prompt.split("\n"):
        if line.startswith("## "):
            if current_lines:
                sections[current_name] = "\n".join(current_lines).strip()
            current_name = line[3:].strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_lines:
        sections[current_name] = "\n".join(current_lines).strip()

    return sections

IDENTITY_SECTIONS = [
    "_preamble",
    "WHO YOU ARE",
    "HOW YOU TALK",
    "YOUR VALUES",
    "HOW YOU HANDLE THINGS",
    "IMPORTANT CONSTRAINTS",
]

KNOWLEDGE_SECTIONS = [
    "WHAT YOU LOVE",
    "YOUR TALENT STACK",
    "YOUR ART",
    "WHAT YOU KNOW (from school)",
    "YOUR KNOWLEDGE (from observations)",
    "YOUR CURIOSITY (what catches your attention)",
    "YOUR PERSONALITY (observed)",
]

DROP_SECTIONS = [
    '"WHAT DO I KNOW?" — RECORD RETRIEVAL',
]

def _truncate_section(name: str, text: str, max_lines: int = 15) -> str:
    """Keep the first max_lines of a section, add truncation marker."""
    lines = text.split("\n")
    if len(lines) <= max_lines:
        return text
    truncated = "\n".join(lines[:max_lines])
    return truncated + f"\n[... {len(lines) - max_lines} more lines — see full Record ...]"

def compress(prompt: str, budget_tokens: int = 4000) -> str:
    """Compress SYSTEM_PROMPT to fit within budget_tokens."""
    sections = _extract_sections(prompt)
    parts: list[str] = []

    for name in IDENTITY_SECTIONS:
        if name in sections:
            content = sections[name]
            if name == "_preamble":
                parts.append(content)
            else:
                parts.append(f"## {name}\n\n{content}")

    current_tokens = _estimate_tokens("\n\n".join(parts))
    remaining = budget_tokens - current_tokens

    for name in KNOWLEDGE_SECTIONS:
        if name not in sections:
            continue
        content = sections[name]
        section_tokens = _estimate_tokens(content)

        if remaining < 200:
            break

        if section_tokens > remaining // len(KNOWLEDGE_SECTIONS):
            max_lines = max(5, remaining // 40)
            content = _truncate_section(name, content, max_lines=max_lines)

        section_text = f"## {name}\n\n{content}"
        parts.append(section_text)
        remaining -= _estimate_tokens(section_text)

    compressed = "\n\n".join(parts)

    actual_tokens = _estimate_tokens(compressed)
    header = (
        f'"""Compressed system prompt for local-first inference.\n\n'
        f"Generated by scripts/compress_system_prompt.py.\n"
        f"Estimated tokens: ~{actual_tokens} (budget: {budget_tokens}).\n"
        f"Full prompt: archive/grace-mar-instance/bot/prompt.py\n"
        f'"""\n\n'
    )

    return compressed, header, actual_tokens

def main() -> None:
    parser = argparse.ArgumentParser(description="Compress SYSTEM_PROMPT for local models")
    parser.add_argument(
        "--budget", type=int, default=4000,
        help="Target token budget (default: 4000)",
    )
    parser.add_argument(
        "--output", "-o", default="archive/grace-mar-instance/bot/prompt_compressed.py",
        help="Output file path (default: archive/grace-mar-instance/bot/prompt_compressed.py)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print stats without writing",
    )
    args = parser.parse_args()

    try:
        from bot.prompt import SYSTEM_PROMPT
    except ImportError:
        print("ERROR: could not import bot.prompt.SYSTEM_PROMPT", file=sys.stderr)
        print("Run from repo root: python scripts/compress_system_prompt.py", file=sys.stderr)
        sys.exit(1)

    full_tokens = _estimate_tokens(SYSTEM_PROMPT)
    compressed, header, actual_tokens = compress(SYSTEM_PROMPT, budget_tokens=args.budget)
    ratio = (1 - actual_tokens / full_tokens) * 100 if full_tokens else 0

    print(f"Full prompt:       ~{full_tokens} tokens")
    print(f"Compressed prompt: ~{actual_tokens} tokens")
    print(f"Reduction:         {ratio:.0f}%")
    print(f"Budget:            {args.budget} tokens")

    if args.dry_run:
        print("\n--- Preview (first 500 chars) ---")
        print(compressed[:500])
        return

    out_path = REPO_ROOT / args.output
    out_path.parent.mkdir(parents=True, exist_ok=True)
    escaped = compressed.replace('"""', r'\"\"\"')
    out_path.write_text(
        header
        + f'SYSTEM_PROMPT_COMPRESSED = """{escaped}"""\n'
    )
    print(f"\nWrote {out_path}")

if __name__ == "__main__":
    main()
