#!/usr/bin/env python3
"""
Build hybrid civ-mem encyclopedia: one fat ENCYCLOPEDIA.md + lib-stubs.yaml.

Default content root: docs/civilization-memory/ (grace-mar–owned). Override --cmc for other trees.
"""

from __future__ import annotations

import argparse
import os
import re
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# Grace-mar–owned essays + optional content/ (not the submodule)
DEFAULT_CMC = REPO_ROOT / "docs" / "civilization-memory"
OUT_DIR_DEFAULT = REPO_ROOT / "users" / "grace-mar" / "artifacts" / "civ-mem-encyclopedia"
SKIP_DIRS = {".git", "node_modules", ".cache", ".skeleton", "apps"}
GITHUB_REPO = os.environ.get("GRACE_MAR_GITHUB_REPO", "rbtkhn/strategy-codex").strip()
GITHUB_PREFIX = f"https://github.com/{GITHUB_REPO}/blob/main/docs/civilization-memory/"


def collect_md(cmc: Path, include_content: bool, essays_only: bool) -> list[Path]:
    """essays_only: cmc/essays/*.md. Else: all *.md under cmc (and cmc/content if --include-content)."""
    out: list[Path] = []
    if essays_only:
        d = cmc / "essays"
        if d.is_dir():
            for p in sorted(d.glob("*.md")):
                out.append(p)
        return out
    for p in sorted(cmc.rglob("*.md")):
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        rel = p.relative_to(cmc)
        if not include_content and rel.parts and rel.parts[0] == "content":
            continue
        out.append(p)
    return sorted(set(out))


def first_heading(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()[:120]
    return ""


def blurb(text: str, n: int = 200) -> str:
    body = re.sub(r"^---.*?---", "", text, count=1, flags=re.DOTALL)
    body = re.sub(r"#[^\n]+\n", "", body)
    one = " ".join(body.split())[:n]
    return one + ("…" if len(one) >= n else "")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--cmc",
        type=Path,
        default=DEFAULT_CMC,
        help="Content root (default: docs/civilization-memory)",
    )
    ap.add_argument("-u", "--user", default="grace-mar")
    ap.add_argument("-o", "--out", type=Path, default=None)
    ap.add_argument(
        "--include-content",
        action="store_true",
        help="Include cmc/content/ when scanning full tree",
    )
    ap.add_argument(
        "--essays-only",
        action="store_true",
        help="Only cmc/essays/*.md → ENCYCLOPEDIA.md (committable)",
    )
    args = ap.parse_args()
    cmc: Path = args.cmc
    out_dir = args.out or (REPO_ROOT / "users" / args.user / "artifacts" / "civ-mem-encyclopedia")
    out_dir.mkdir(parents=True, exist_ok=True)
    if args.essays_only:
        enc_path = out_dir / "ENCYCLOPEDIA.md"
        stubs_path = out_dir / "lib-stubs.yaml"
    elif args.include_content:
        enc_path = out_dir / "ENCYCLOPEDIA.content.md"
        stubs_path = out_dir / "lib-stubs.content.yaml"
    else:
        enc_path = out_dir / "ENCYCLOPEDIA.docs.md"
        stubs_path = out_dir / "lib-stubs.docs.yaml"

    if not cmc.is_dir():
        print(f"Content root missing: {cmc}", flush=True)
        return 1

    files = collect_md(cmc, args.include_content, args.essays_only)
    lines = [
        f"# Civ-mem encyclopedia (generated {date.today().isoformat()})",
        "",
        f"_Source tree: `{cmc.relative_to(REPO_ROOT)}` — regen after edits; do not edit this file by hand._",
        "",
    ]
    stub_lines = ["# Generated stubs — merge to self-library only after gate", ""]
    rel_base = cmc.resolve()

    for i, path in enumerate(files):
        rel = path.relative_to(rel_base)
        text = path.read_text(encoding="utf-8", errors="replace")
        anchor = f"CM:{rel.as_posix()}"
        title = first_heading(text) or rel.stem.replace("-", " ").title()
        scope_bits = [rel.parts[0] if rel.parts else "root", rel.stem.lower().replace("_", "-")]
        if "essays" in rel.parts:
            scope_bits.append("essays")
        scope_bits.append("grace_mar_owned")
        scope_unique = []
        for s in scope_bits:
            if s and s not in scope_unique:
                scope_unique.append(s)
        scopes = ", ".join(f'"{s}"' for s in scope_unique[:8])
        bl = blurb(text).replace('"', "'")
        gh = f"{GITHUB_PREFIX}{rel.as_posix()}"

        lines.append(f"## {anchor}")
        lines.append("")
        lines.append(f"*Path:* `docs/civilization-memory/{rel.as_posix()}`")
        lines.append("")
        lines.append(text.strip())
        lines.append("")
        lines.append("---")
        lines.append("")

        stub_lines.append(f"  # {rel.as_posix()}")
        stub_lines.append("  - id: LIB-NNNN")
        stub_lines.append(f'    title: "Civ-mem — {title}"')
        stub_lines.append('    author: "grace-mar"')
        stub_lines.append('    lane: "reference"')
        stub_lines.append('    type: "article"')
        stub_lines.append('    status: "active"')
        stub_lines.append('    engagement_status: "trusted"')
        stub_lines.append('    lookup_priority: "medium"')
        stub_lines.append(f"    scope: [{scopes}]")
        stub_lines.append('    source: "url"')
        stub_lines.append(f'    url: "{gh}"')
        stub_lines.append(f"    added_at: {date.today().isoformat()}")
        stub_lines.append(f'    notes: "## {anchor} in ENCYCLOPEDIA.md. {bl}"')
        stub_lines.append("")

    enc_path.write_text("\n".join(lines), encoding="utf-8")
    stubs_path.write_text("\n".join(stub_lines), encoding="utf-8")
    print(f"Wrote {enc_path} ({len(files)} sources)")
    print(f"Wrote {stubs_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
