#!/usr/bin/env python3
"""
Re-generate a daily brief, then re-apply operator post-process tails.

Default tail anchor: "## 2c. Narrative layer retrofit" through end-of-file on the
existing brief. The regenerated base is written to a temp path, the tail is
spliced after **## 2b** (Civ-mem depth hooks), then the result replaces the target
brief.

If an older brief folded the generator outline (**## 3**–**## 7** stubs) after **## 2c**,
the same stubs also appear in the fresh generator output; this script strips that
duplicate **## 3**–**## 7** block from the preserved tail when it sits immediately
before **## 8. Quality rubric footer** (optional).

This is an operator convenience script — it does not change Record surfaces.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
POSTPROCESS_ANCHOR = "## 2c. Narrative layer retrofit"
# Generator stub duplicated inside some post-##2c tails (before ## 8).
STUB_LEAD_THEMES = "\n## 3. Lead themes (auto-stub — replace after reading)"
# Copied from tails saved when the brief already ended with the generator footer.
_TAIL_GEN_SIG = re.compile(
    r"\n\n---\s*\n\n_Generated by `scripts/generate_work_politics_daily_brief\.py`"
    r" \(legacy alias: `generate_wap_daily_brief\.py`\); config `[^`]+`\._\s*\Z",
    re.DOTALL,
)

def _validate_iso_day(day: str) -> None:
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", day):
        raise SystemExit("error: --date must be YYYY-MM-DD")

def _extract_tail(text: str) -> str | None:
    idx = text.find(POSTPROCESS_ANCHOR)
    if idx == -1:
        return None
    return text[idx:].lstrip("\n")

def _sanitize_postprocess_tail(tail: str) -> str:
    """Drop duplicate ## 3–## 7 outline accidentally stored after ## 2c (keeps ## 8+)."""
    if STUB_LEAD_THEMES not in tail:
        return tail
    i = tail.find(STUB_LEAD_THEMES)
    j = tail.find("\n## 8. Quality rubric footer", i)
    if j == -1:
        return tail
    return tail[:i].rstrip() + tail[j:]

def _strip_trailing_generator_signature(tail: str) -> str:
    """Remove a trailing generator `_Generated by ...` block from the tail (base already emits it)."""
    m = _TAIL_GEN_SIG.search(tail)
    if not m:
        return tail
    return tail[: m.start()].rstrip() + "\n"

def _strip_existing_tail(text: str) -> str:
    idx = text.find(POSTPROCESS_ANCHOR)
    if idx == -1:
        return text
    return text[:idx].rstrip() + "\n"

def _merge(base: str, tail: str) -> str:
    base_stripped = base.rstrip() + "\n"
    if POSTPROCESS_ANCHOR in base_stripped and tail not in ("", None):
        # Caller should pass --force if they want replacement.
        raise SystemExit(
            f"error: generated base already contains {POSTPROCESS_ANCHOR!r}; "
            "refuse to duplicate without --force"
        )
    return base_stripped.rstrip() + "\n\n" + tail.lstrip("\n").rstrip() + "\n"

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate daily brief and merge ## 2c+ post-process tail"
    )
    parser.add_argument("-u", "--user", default="grace-mar", help="User id")
    parser.add_argument(
        "--date",
        required=True,
        metavar="YYYY-MM-DD",
        help="Brief calendar day (passed through to --brief-date)",
    )
    parser.add_argument(
        "--brief-path",
        default="",
        help="Target brief path (default: docs/skill-work/work-strategy/daily-brief-YYYY-MM-DD.md)",
    )
    parser.add_argument(
        "--no-fetch",
        action="store_true",
        help="Forward --no-fetch to generator (offline RSS skip)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help=f"If regenerated base already contains {POSTPROCESS_ANCHOR!r}, strip it before merge",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print merged output path only / do not write target",
    )
    args = parser.parse_args()

    day = args.date
    _validate_iso_day(day)

    if args.brief_path:
        target = Path(args.brief_path).resolve()
    else:
        target = (
            REPO_ROOT
            / "docs"
            / "skill-work"
            / "work-strategy"
            / f"daily-brief-{day}.md"
        ).resolve()

    if not target.is_file():
        print(f"error: target brief not found: {target}", file=sys.stderr)
        return 2

    old_text = target.read_text(encoding="utf-8")
    tail = _extract_tail(old_text)
    if tail is None:
        print(
            f"error: no tail found (missing {POSTPROCESS_ANCHOR!r}): {target}",
            file=sys.stderr,
        )
        return 2

    tail = _sanitize_postprocess_tail(tail)
    tail = _strip_trailing_generator_signature(tail)

    gen = REPO_ROOT / "scripts" / "generate_work_politics_daily_brief.py"
    if not gen.is_file():
        print(f"error: generator not found: {gen}", file=sys.stderr)
        return 2

    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        suffix=f"-daily-brief-{day}-regen.md",
        delete=False,
    ) as tmp:
        tmp_path = Path(tmp.name)

    cmd = [
        sys.executable,
        str(gen),
        "-u",
        args.user,
        "--brief-date",
        day,
        "-o",
        str(tmp_path),
    ]
    if args.no_fetch:
        cmd.append("--no-fetch")

    try:
        subprocess.run(cmd, cwd=REPO_ROOT, check=True)
    except subprocess.CalledProcessError as exc:
        print(f"error: generator failed ({exc.returncode})", file=sys.stderr)
        return exc.returncode

    base = tmp_path.read_text(encoding="utf-8")
    if args.force:
        base = _strip_existing_tail(base)

    merged = _merge(base, tail)

    if args.dry_run:
        print(f"dry-run: would write: {target}")
        tmp_path.unlink(missing_ok=True)
        return 0

    target.write_text(merged, encoding="utf-8")
    tmp_path.unlink(missing_ok=True)
    print(target)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
