#!/usr/bin/env python3
"""Create a dated Moonshot Contribution Map from the WORK-only template (stdlib only).

Does not touch Record surfaces, moonshot-dashboard.md, or the network.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SLUG_OK = re.compile(r"^[a-z0-9][a-z0-9_-]*$")

DEFAULT_TEMPLATE = (
    REPO_ROOT
    / "docs"
    / "skill-work"
    / "work-strategy"
    / "modules"
    / "moonshot-orchestration"
    / "moonshot-map-template.md"
)
DEFAULT_OUT_DIR = (
    REPO_ROOT
    / "docs"
    / "skill-work"
    / "work-strategy"
    / "modules"
    / "moonshot-orchestration"
    / "maps"
)

GENERATED_HEADER = (
    "<!--\n"
    "Generated by scripts/new_moonshot_map.py\n"
    "Surface: WORK-only\n"
    "Record status: Not Record truth\n"
    "Dashboard status: Not auto-added\n"
    "-->\n\n"
)

def validate_slug(slug: str) -> str:
    s = (slug or "").strip()
    if not s:
        print("error: --slug is required and must be non-empty", file=sys.stderr)
        sys.exit(1)
    for bad in ("/", "\\", "..", " ", "\t", "\n", "\r"):
        if bad in s:
            print(
                "error: --slug must not contain path separators, whitespace, or '..'",
                file=sys.stderr,
            )
            sys.exit(1)
    if not SLUG_OK.match(s):
        print(
            "error: --slug must start with a letter or digit, then only "
            "a-z, 0-9, hyphen, and underscore",
            file=sys.stderr,
        )
        sys.exit(1)
    return s

def title_from_slug(slug: str) -> str:
    return " ".join(p.capitalize() for p in re.split(r"[-_]+", slug) if p)

def load_template(path: Path) -> str:
    if not path.is_file():
        print(f"error: template is not a file: {path}", file=sys.stderr)
        sys.exit(1)
    return path.read_text(encoding="utf-8")

def render_map(template: str, title: str) -> str:
    body = template

    def _name_repl(m: re.Match[str]) -> str:
        return f"{m.group(1)} {title}\n\n"

    if not re.search(r"(\*\*Name:\*\*)\s*\n\s*\n", body):
        print("error: template missing expected '**Name:**' block", file=sys.stderr)
        sys.exit(1)
    body = re.sub(r"(\*\*Name:\*\*)\s*\n\s*\n", _name_repl, body, count=1)

    if not re.search(r"(\*\*Current status:\*\*)\s*\n\s*\n", body):
        print("error: template missing expected '**Current status:**' block", file=sys.stderr)
        sys.exit(1)
    body = re.sub(
        r"(\*\*Current status:\*\*)\s*\n\s*\n",
        r"\1 Draft map\n\n",
        body,
        count=1,
    )

    if "**Claim strength:** Tier A / Tier B / Tier C / Tier D" not in body:
        print("error: template missing expected '**Claim strength:**' tier line", file=sys.stderr)
        sys.exit(1)
    body = body.replace(
        "**Claim strength:** Tier A / Tier B / Tier C / Tier D",
        "**Claim strength:** Tier D",
        1,
    )

    return GENERATED_HEADER + body

def resolve_repo_path(p: Path) -> Path:
    if p.is_absolute():
        return p.resolve()
    return (REPO_ROOT / p).resolve()

def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Create a dated Moonshot Contribution Map from the template (non-authoritative)."
    )
    ap.add_argument("--slug", required=True, help="kebab or snake name (a-z, 0-9, -, _)")
    ap.add_argument(
        "--date",
        default=None,
        help="YYYY-MM-DD (default: today, local system date)",
    )
    ap.add_argument(
        "--title",
        default=None,
        help="Map title (default: derived from --slug)",
    )
    ap.add_argument(
        "--template",
        type=Path,
        default=DEFAULT_TEMPLATE,
        help="path to map template (default: moonshot-orchestration/moonshot-map-template.md)",
    )
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help="output directory (default: moonshot-orchestration/maps/)",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="print target path and preview; do not write",
    )
    ap.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing file if present",
    )
    return ap.parse_args()

def main() -> int:
    args = parse_args()
    slug = validate_slug(args.slug)
    if args.date:
        date_str = args.date.strip()
        try:
            date.fromisoformat(date_str)
        except ValueError:
            print("error: --date must be YYYY-MM-DD", file=sys.stderr)
            return 1
    else:
        date_str = date.today().isoformat()
    title = (args.title or "").strip() or title_from_slug(slug)
    tpath = resolve_repo_path(Path(args.template))
    out_dir = resolve_repo_path(Path(args.out_dir))
    out_path = out_dir / f"{date_str}-{slug}.md"

    try:
        out_path.resolve().relative_to(REPO_ROOT)
    except ValueError:
        print("error: output path must stay inside the repository", file=sys.stderr)
        return 1

    text = load_template(tpath)
    final_text = render_map(text, title)

    if out_path.is_file() and not args.force:
        print(
            f"error: file exists (use --force to overwrite): {out_path.relative_to(REPO_ROOT)}",
            file=sys.stderr,
        )
        return 1

    if args.dry_run:
        print(str(out_path.relative_to(REPO_ROOT)))
        print("---")
        for line in final_text.splitlines()[:40]:
            print(line)
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path.write_text(final_text, encoding="utf-8", newline="\n")
    print(out_path.relative_to(REPO_ROOT).as_posix())
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
